### ISSUE TITLE
Does this support expansion of patterns or globs?

### ISSUE THREAD

**Issue by muliyul** [tj-actions/verify-changed-files#10]
Example:

```
- name: Verify changed SQL files
        uses: tj-actions/verify-changed-files@v5
        id: changed_files
        with:
          files: |
             *.sql
      - name: Perform action when files change.
        if: steps.changed_files.outputs.files_changed == 'true'
        run: |
          echo "Do something when SQL files have changed."
```
