### ISSUE TITLE
Possible to use this action to detect when files are deleted?

### ISSUE THREAD

**Issue by AndrewLane** [tj-actions/verify-changed-files#180]
As far as I can tell, if the only operation that happens to the file system is that a file or files are deleted, then files_changed will return 'false'.  Is that accurate?  If so, any workarounds that you can think of to detect when any file changes happen (modification, addition, or deletion)?

**Comment by AndrewLane** [comment]
If it helps, my use case for this action is to supplement other parts of my workflow that are generating documentation markdown files.  In the case where some documentation no longer applies and needs to be deleted, I'm looking to use automation to detect when this file is deleted by a script further up the chain.

**Comment by jackton1** [comment]
> As far as I can tell, if the only operation that happens to the file system is that a file or files are deleted, then files_changed will return 'false'. Is that accurate? If so, any workarounds that you can think of to detect when any file changes happen (modification, addition, or deletion)?

That’s correct and this seems like a valid use case, I’ve added support for detecting deleted files, it should be available in the latest release.

**Comment by tvdijen** [comment]
Maybe I'm doing something wrong, but it still won't detected files that were deleted during the workflow...

![afbeelding](https://user-images.githubusercontent.com/841045/202899438-6fcf9f45-0510-492c-b68b-08b9dfa36ea2.png)

I've tried with different glob `public/**` as well, but no difference... Adding or modifying files anywhere in the `public/` directory will be detected, just not the removed files.

**Comment by shinebayar-g** [comment]
Does this still work?

```yaml
name: Build

on:
  push:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - run: |
          rm README.md
          echo "new file" > new-file.txt

      - name: Check changed files
        id: changed-files
        uses: tj-actions/verify-changed-files@v16

      - name: Print changed files
        run: |
          for file in ${{ steps.changed-files.outputs.changed_files }}; do
            echo "file: $file"
            echo "------"
          done

      - run: git status
```

It's not detecting deleted files. But successfully detected a new file.

![image](https://github.com/tj-actions/verify-changed-files/assets/3091558/bb184743-a2fd-4839-b09f-beb705ee646e)
