### ISSUE TITLE
[BUG] Except pattern not working

### ISSUE THREAD

**Issue by emepetres** [tj-actions/verify-changed-files#201]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

Docs says it supports Glob pattern, however this small test failed with dll changes inside Generator folder (not direct child of Generator):

```yaml
- name: Verify Changed files
        uses: tj-actions/verify-changed-files@v10.1
        id: verify-changed-files
        with:
          files: |
            Generator
            !*.dll
```

### To Reproduce

1. Modify only a file you want this action to be ignored (e.g. binfile.bin)
2. Use the action and setup the file !*.bin
3. ´files_changed´ should be false, however it is true

### What OS are you seeing the problem on?

windows-latest or windows-2019

### Expected behavior?

Files with pattern `!` should be ignored by the action

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
