### ISSUE TITLE
[BUG] Action fails when output separator requested is newline (`\n`)

### ISSUE THREAD

**Issue by kunaltyagi** [tj-actions/verify-changed-files#286]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

Action fails while setting output

### To Reproduce

```
    - name: Find changed files
      uses: tj-actions/verify-changed-files@v14.0.1
      id: artifacts
      with:
        files: '*'
        separator: '\n'
```

### What OS are you seeing the problem on?

ubuntu-latest or ubuntu-20.04

### Expected behavior?

Proper handling of newline (or documentation to state it's not possible)

### Relevant log output

![image](https://user-images.githubusercontent.com/2657068/232949572-f6b54717-712f-4457-bf38-3188899668c5.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
