### ISSUE TITLE
[BUG] No changes found even if I commit changes on the specified files

### ISSUE THREAD

**Issue by thierryskoda** [tj-actions/verify-changed-files#291]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

Here's what I'm using in my Github action:

```
- name: Verify Changed files
        uses: tj-actions/verify-changed-files@v14
        id: verify-changed-files
        with:
          files: |
            apps/hcp-app/version.json
            yarn.lock
```

This action is triggered on every commit on the branch `main`.

I tried many times to push changes on `yarn.lock` or `apps/hcp-app/version.json` but it always says `no changes found`

Here are some screenshot from the Github action

<img width="493" alt="image" src="https://user-images.githubusercontent.com/6875849/233223455-35edbe60-6a43-43aa-b747-43c5439e1412.png">

<img width="197" alt="image" src="https://user-images.githubusercontent.com/6875849/233223500-4fa6898a-be47-421b-97ec-12f7e2fd6477.png">

### To Reproduce

1. Create a monorepo
2. Create 1 package with the file `version.json` (apps/hcp-app/version.json)
3. Create the GitHub action with this step:
```
- name: Verify Changed files
        uses: tj-actions/verify-changed-files@v14
        id: verify-changed-files
        with:
          files: |
            apps/hcp-app/version.json
            yarn.lock
```
4. Make your Github action run on every push to the main branch
5. Edit the `version.json` file and push to main
6. Wait for the job to finish and look if the step detected the changes

### What OS are you seeing the problem on?

ubuntu-latest or ubuntu-20.04

### Expected behavior?

I expected to see that `yarn.lock` has changed.

### Relevant log output

```shell
Uploaded in the description above
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
