### ISSUE TITLE
[BUG] Unable to match when the changed file name is Chinese characters

### ISSUE THREAD

**Issue by Z1Turn0** [tj-actions/verify-changed-files#370]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

When the changed file name is Chinese characters,  *.outputs.changed_files is empty.

### To Reproduce

```
    steps:
      - uses: actions/checkout@v4

      - name: Change text file
        run: |
          echo "Modified" > 啊啊啊.cpp

      - name: Verify Changed files
        uses: tj-actions/verify-changed-files@v17
        id: verify-changed-files
        with:
          files: |
            *.cpp

      - name: Run step only when any of the above files change.
        if: steps.verify-changed-files.outputs.files_changed == 'true'
        env:
          CHANGED_FILES: ${{ steps.verify-changed-files.outputs.changed_files }}
        run: |
          echo "Changed files: $CHANGED_FILES"
```
" Run step only when any of the above files change" won't run.

### What OS are you seeing the problem on?

ubuntu-latest or ubuntu-22.04

### Expected behavior?

Support Chinese characters. : ( 

### Relevant log output

```shell
##[debug]..Evaluating String:
##[debug]..=> 'changed_files'
##[debug]=> null
##[debug]Result: null
##[debug]Finishing: Verify Changed files
```

### Has all relevant logs been included?

- [X] I've included all relevant logs

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
