### ISSUE TITLE
[BUG] Not detecting the change on a file

### ISSUE THREAD

**Issue by genieai-vikas** [tj-actions/verify-changed-files#69]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug?

This is my workflow:

```
      - name: Verify rootAlpine Dockerfile changed
        uses: tj-actions/verify-changed-files@v7.1
        id: root_apline_changed_files
        with:
          files: |
            docker/rootAlpine
      - name: Run step only when files change.
        if: steps.root_apline_changed_files.outputs.files_changed == 'true'
        run: |
          echo "Changed files: ${{ steps.root_apline_changed_files.outputs.changed_files }}"
```

I have a Dockerfile inside docker/rootAlpine which I am changing but on github I am getting 
`No changes found at: docker/rootAlpine`

ideally, It should have been that change is found at docker/rootAlpine

P.S I have also tried with docker/rootAlpine/Dockerfile but still the same result.

### To Reproduce

Have a Dockerfile in docker/rootAlpine and modify it and try to detect the change

### What OS are you seeing the problem on?

ubuntu-latest or ubuntu-20.04

### Expected behavior?

ubuntu

### Relevant log output

```shell
Run tj-actions/verify-changed-files@v7.1
Checking for file changes: "docker/rootAlpine"...
No changes found at: docker/rootAlpine
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jackton1** [comment]
If your changing the file inside the github actions workflow step you should be able to see changes

```yaml
...
      - name: Change file in directory
        run: |
          echo "Changed" > test_directory/new.txt

      - name: Verify Changed files
        uses: tj-actions/verify-changed-files@v7.1
        id: verify-changed-files
        with:
          files: |
             test_directory
```


If your making changes to a file that are committed to the branch you might be looking for the [changed-files](https://github.com/tj-actions/changed-files) action instead.
